<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup Label="General Properties">
		<TargetFrameworks>net10.0;net8.0;net481;net472</TargetFrameworks>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<IsAotCompatible>true</IsAotCompatible>

		<OutputType>Library</OutputType>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>

		<RootNamespace>OceanApocalypseStudios.RSML.Extensibility</RootNamespace>
	</PropertyGroup>

	<PropertyGroup Label="NuGet Package Setup">
		<GeneratePackageOnBuild>True</GeneratePackageOnBuild>

		<PackageId>OceanApocalypseStudios.RSML.Extensibility</PackageId>
		<Title>RSML Extensibility SDK</Title>
		<Description>Extensibility and modularity support for OceanApocalypseStudios' RSML.</Description>

		<PackageProjectUrl>https://oceanapocalypsestudios.org/rsml-docs/</PackageProjectUrl>
		<PackageIcon>icon.png</PackageIcon>
		<RepositoryUrl>https://github.com/OceanApocalypseStudios/RedSeaMarkupLanguage/</RepositoryUrl>
		<PackageTags>markup;language;logic;logic-path;system;host;rsml;rsea;decision;oss</PackageTags>
		<PackageReadmeFile>README.md</PackageReadmeFile>
	</PropertyGroup>

	<PropertyGroup Label="Debug Build" Condition="'$(Configuration)' == 'Debug'">
		<DebugType>full</DebugType>
		<CheckForOverflowUnderflow>True</CheckForOverflowUnderflow>
	</PropertyGroup>

	<PropertyGroup Label="Release (Optimized) Build" Condition="'$(Configuration)' == 'Release'">
		<DebugType>none</DebugType>
		<Optimize>true</Optimize>
	</PropertyGroup>

	<ItemGroup Label="Resources">
		<None Include="..\..\assets\icon.png">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
			<Visible>false</Visible>
		</None>
		<None Include="..\..\README.md">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
			<Visible>false</Visible>
		</None>
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="System.Collections.Immutable" Version="10.0.10" />
		<PackageReference Include="System.Memory" Version="4.6.3" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\RSML\RSML.csproj" />
	</ItemGroup>

</Project>
