<!--
Note for future self:
- These properties are shared between all projects in the solution;
- Any property defined here can be explicitly overridden in any of said projects.
-->
<Project>
	<!-- XXX: Change all of these on a new version -->
	<PropertyGroup>
		<SemVerMajor>3</SemVerMajor> <!-- major only (e.g.: 3 for v3.0.0) -->
		<VersionPrefix>3.0.0</VersionPrefix> <!-- major.minor.patch -->
		<VersionSuffix>prerelease1</VersionSuffix> <!-- pre-release suffix without hyphen (beta, alpha, prereleaseX) or empty if stable -->
		<PackageReleaseNotes>TODO</PackageReleaseNotes> <!-- release notes -->
	</PropertyGroup>

	<!-- Common attributes for all projects under this solution. -->
	<PropertyGroup>
		<Nullable>enable</Nullable>
		<LangVersion>14</LangVersion>
		<Platforms>AnyCPU;ARM64;x64;x86;ARM32</Platforms>

		<!-- NuGet Package Setup -->
		<Authors>OceanApocalypseStudios</Authors>
		<Company>OceanApocalypseStudios</Company>
		<Copyright>Copyright 2025-2026 OceanApocalypseStudios</Copyright>
		<PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
		<RepositoryType>git</RepositoryType>
		<PackageRequireLicenseAcceptance>true</PackageRequireLicenseAcceptance>
		<NeutralLanguage>en</NeutralLanguage>
	</PropertyGroup>

	<!-- Attributes for solution-wise code analysis. -->
	<PropertyGroup>
		<AnalysisLevel>latest-all</AnalysisLevel>
		<AnalysisMode>All</AnalysisMode>

		<!-- CA1016 leads to false positives after running dotnet clean (though it fixes itself on build) -->
		<NoWarn>$(NoWarn);CA1016</NoWarn>
	</PropertyGroup>

	<!-- Don't make changes to this group. Everything is determined from data above. -->
	<ItemGroup>
		<AssemblyMetadata Include="SemVersion" Value="$(VersionPrefix)"
						  Condition="'$(VersionSuffix)' == ''" />
		<AssemblyMetadata Include="SemVersion" Value="$(VersionPrefix)-$(VersionSuffix)"
						  Condition="'$(VersionSuffix)' != ''" />
	</ItemGroup>

	<!--
	Don't make changes to this group.
	This sets the GitHub Workflow Run Number environment variable if it doesn't exist.
	This is here because local builds shouldn't break or be faulty because of an unset env var.
	-->
	<PropertyGroup>
		<GITHUB_RUN_NUMBER Condition="'$(GITHUB_RUN_NUMBER)' == ''">0</GITHUB_RUN_NUMBER>
	</PropertyGroup>

	<!-- Don't make changes to this group. Everything is determined from data above. -->
	<PropertyGroup>
		<AssemblyVersion>$(SemVerMajor).0.0.0</AssemblyVersion>
		<FileVersion>$(VersionPrefix).$(GITHUB_RUN_NUMBER)</FileVersion>
	</PropertyGroup>
</Project>