<Project>
	<PropertyGroup>
		<ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
	</PropertyGroup>

	<ItemGroup>
		<!-- CLI -->
		<PackageVersion Include="SixLabors.ImageSharp" Version="3.1.12" />
		<PackageVersion Include="Spectre.Console" Version="0.57.2" />
		<PackageVersion Include="System.CommandLine" Version="2.0.10" />
		
		<!-- Tests and benchmarks -->
		<PackageVersion Include="xunit.v3.mtp-v2" Version="3.2.2" />
		<PackageVersion Include="Microsoft.Testing.Extensions.CodeCoverage" Version="18.9.0" />
		<PackageVersion Include="BenchmarkDotNet" Version="0.15.8" />
		<PackageVersion Include="BenchmarkDotNet.Diagnostics.Windows" Version="0.15.8" Condition="'$(OS)' == 'Windows_NT'" />
	</ItemGroup>
</Project>