<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<OutputType>Exe</OutputType>
		<ImplicitUsings>enable</ImplicitUsings>
		
		<IsTestProject>true</IsTestProject>
		<TestingPlatformDotnetTestSupport>true</TestingPlatformDotnetTestSupport>
		<UseMicrosoftTestingPlatformRunner>true</UseMicrosoftTestingPlatformRunner>

		<RootNamespace>OceanApocalypseStudios.RSML.Tests.Native</RootNamespace>
		<LangVersion>latest</LangVersion>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>

		<Platforms>AnyCPU;ARM64;x64;x86</Platforms>
	</PropertyGroup>

	<ItemGroup>
		<Content Include="xunit.runner.json" CopyToOutputDirectory="PreserveNewest" />
	</ItemGroup>

	<ItemGroup>
		<Using Include="Xunit" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="xunit.v3.mtp-v2" Version="3.2.2" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\src\RSML.Native\RSML.Native.csproj" />
		<ProjectReference Include="..\..\src\RSML\RSML.csproj" />
	</ItemGroup>

</Project>
