<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<OutputType>Exe</OutputType>
		<UseMicrosoftTestingPlatformRunner>true</UseMicrosoftTestingPlatformRunner>
		<RootNamespace>OceanApocalypseStudios.RSML.Tests.Internal</RootNamespace>
		<LangVersion>latest</LangVersion>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<Platforms>AnyCPU;ARM64;x64;x86;ARM32</Platforms>
	</PropertyGroup>

	<ItemGroup>
		<Content Include="xunit.runner.json" CopyToOutputDirectory="PreserveNewest" />
	</ItemGroup>

	<ItemGroup>
		<Using Include="Xunit" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="xunit.v3.mtp-v2" />
		<PackageReference Include="Microsoft.Testing.Extensions.CodeCoverage" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\src\RSML\RSML.csproj" />
	</ItemGroup>

</Project>
