<!-- NuGet Packaging -->
<Project>
	<PropertyGroup>
		<GeneratePackageOnBuild>True</GeneratePackageOnBuild>

		<PackageId>OceanApocalypseStudios.RSML</PackageId>
		<Title>Red Sea Markup Language</Title>
		<Authors>OceanApocalypseStudios</Authors>
		<Company>OceanApocalypseStudios</Company>
		<NeutralLanguage>en</NeutralLanguage>

		<!-- DON'T FORGET TO EDIT THIS -->
		<PackageReleaseNotes>TODO</PackageReleaseNotes>

		<Description>The only markup language that dynamically interprets different logic paths based on an host's OS and CPU architecture.</Description>
		<Copyright>Copyright (c) 2025 OceanApocalypseStudios</Copyright>
		<PackageProjectUrl>https://oceanapocalypsestudios.org/rsml-docs/</PackageProjectUrl>
		<PackageIcon>icon.png</PackageIcon>
		<RepositoryUrl>https://github.com/OceanApocalypseStudios/RedSeaMarkupLanguage/</RepositoryUrl>
		<RepositoryType>git</RepositoryType>
		<PackageTags>markup;language;logic;logic-path;system;host;rsml;rsea;decision;oss</PackageTags>
		<PackageRequireLicenseAcceptance>true</PackageRequireLicenseAcceptance>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
	</PropertyGroup>
</Project>
