<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<RootNamespace>OceanApocalypseStudios.RSML.Native</RootNamespace>
		<OutputType>Library</OutputType>

		<!-- Native Publishing -->
		<PublishAot>true</PublishAot>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<NativeLib>Shared</NativeLib>
		<InvariantGlobalization>true</InvariantGlobalization>
		<TieredCompilation>true</TieredCompilation>
		<PublishSingleFile>false</PublishSingleFile>

		<Platforms>AnyCPU;ARM64;x64;x86</Platforms>
	</PropertyGroup>

	<ItemGroup Label="Resources">
		<None Include="..\..\assets\icon.png">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
			<Visible>false</Visible>
		</None>
		<None Include="..\..\README.md">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
			<Visible>false</Visible>
		</None>
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="JetBrains.Annotations" Version="2026.2.0" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\RSML.Extensibility\RSML.Extensibility.csproj" />
		<ProjectReference Include="..\RSML\RSML.csproj" />
	</ItemGroup>

</Project>
