<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<RootNamespace>OceanApocalypseStudios.RSML.Native</RootNamespace>
		<OutputType>Library</OutputType>

		<!-- Native Publishing -->
		<PublishAot>true</PublishAot>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<NativeLib>Shared</NativeLib>
		<InvariantGlobalization>true</InvariantGlobalization>
		<TieredCompilation>true</TieredCompilation>
		<PublishSingleFile>false</PublishSingleFile>
	</PropertyGroup>

	<PropertyGroup Label="NuGet Package Setup">
		<PackageId>OceanApocalypseStudios.RSML.Native</PackageId>
		<Title>RSML Native ABI</Title>

		<Description>Native C interopability for RSML.</Description>
		<PackageProjectUrl>https://oceanapocalypsestudios.org/rsml-docs/</PackageProjectUrl>
		<PackageIcon>icon.png</PackageIcon>
		<RepositoryUrl>https://github.com/OceanApocalypseStudios/RedSeaModernLanguage/</RepositoryUrl>
		<PackageTags>DSL;native;interop;c;cpp;c++;language;logic;logic-path;rsml;rsea;decision;oss</PackageTags>
		<PackageReadmeFile>README.md</PackageReadmeFile>
	</PropertyGroup>

	<ItemGroup Label="Resources">
		<None Include="..\..\assets\icon.png">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
			<Visible>false</Visible>
		</None>
		<None Include="..\..\README.md">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
			<Visible>false</Visible>
		</None>
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\RSML\RSML.csproj" />
	</ItemGroup>

</Project>