#+TITLE: Red Sea Markup Language Official Documentation
#+AUTHOR: Matthew (MF366)
#+DESCRIPTION: The welcome page for the RSML Documentation.

* 👋 Welcome!
This is the official documentation for *RSML* (Red Sea Markup Language), *the* modern fork of MFRoad, but up to ten times better.

* 💗 Contributing
If you wish to contribute to the documentation, we'd really appreciate it. However, there are some rules and guidelines you must follow:
- *KISS: Keep It Simple, Stupid.* Make sure your changes do not affect the simplicity and readability of the documentation in a negative way.
- *If it ain’t broken, don’t redesign it.* Do not propose changes to how the UI should look, as the current combination of HTML and CSS aims for simplicity, due to the fact it's very objective.
- *Editing the HTML export is like painting a screenshot — impressive, but pointless.* Make /Pull Requests/ for the ~Org~ files, not the ~HTML~ ones.
- *Fixing typos is noble; flooding PRs with them is chaos.* Typo squatting is perfectly fine and helpful, but don't make too many /Pull Requests/ to fix typos in a row, as it causes unnecessary spam. The best alternative is to "bundle" several typo fixes in one PR.
- *There are no stupid questions — only unanswered ones (and I try to avoid those).* If you have any questions, don't hesitate to ask, as I try to reply to all. You can use the following e-mail: [[mailto:real_mf366@yahoo.com][~real_mf366@yahoo.com~]].

If those rules did not scare you away, the GitHub repository is [[https://github.com/OceanApocalypseStudios/RedSeaMarkupLanguage][right here]]. Thanks ahead for your contributions.

* 🔧 How to Build
To build this documentation, simply run =RSML.Docs.exe= or =RSML.Docs=. Yea, it's *that* easy.

You may also specify a custom build filetype (such as *PDF (with LaTeX)*):

#+begin_src bash
# These ones stand for PDF
>> RSML.Docs pdf
>> RSML.Docs latex

# These ones, Markdown
>> RSML.Docs markdown
>> RSML.Docs mdown

# HTML is default so you don't need to specify it
>> RSML.Docs html
#+end_src

* 👉 Documentation Modules
Below, you can find an ordered list of all the different modules in this documentation.

- [[file:RSML_Language_Standards/ReadMeFirst.org][*Language Standards*]]
- [[file:Migrate_From_MFRoad/ReadMeFirst.org][*Migrating from MFRoad*]]
- TODO: add more modules
