#+title: mfroad-like Language Standard Reference Sheet
#+author: Matthew (MF366)
#+description: The mfroad-like language standard for RSML.

#+options: toc:nil

#+TOC: headlines 3

[[file:../GlobalIndex.org][*â—€ Global Navigation*]]
[[file:ReadMeFirst.org][*â—€ Go back*]]

* ðŸ”§ Operators
~mfroad-like~ defines the following operators, ordered from primary to tertiary:
- =???=
- =<<=
- =!!!= 

* ðŸ’¡ Main Actions
~mfroad-like~ defines all three actions as indicated below:

| Operator Type | Action that's performed                   |
|---------------+-------------------------------------------|
| Secondary     | Outputs the value suceeding it.           |
| Tertiary      | Throws an error with a specified message. |

* ðŸŽ¯ Special Actions
~mfroad-like~ does not define any special actions whatsoever.

#+begin_quote
*Remember:* =@EndAll= is already built-in into RSML.
#+end_quote

* â“ So why use this standard?
Use this standard when you want:
- [X] *Simplicity.* Since ~mfroad-like~ only defines the absolutely necessary, you don't waste time learning specific features.
- [X] *Easy migration.* If you're coming from MFRoad, this is the closest standard you'll have to it.

However, you may want to use a different parser if you want:
- [ ] *Features.* ~mfroad-like~ is quite limited in terms of features - it doesn't even have any *special actions*.
- [ ] *Custom operators (and/or actions).* If you don't like this standard's operators (and/or actions), you might want to customize them.
