#+title: Red Sea Markup Language for C#
#+author: Matthew (MF366)
#+description: The welcome page for the RSML for C# documentation module.

#+options: toc:nil

#+TOC: headlines 3

[[file:../GlobalIndex.org][*◀ Global Navigation*]]
[[file:../ReadMeFirst.org][*◀ Go back*]]

* 👋 Welcome!
This is the official documentation module for the *Red Sea Markup Language for C#*.

* 💾 Installing
There are multiple ways of using RSML in your C# programs.

** 🟢 NuGet Package (.NET CLI)
To download the latest stable version of RSML from NuGet, simply run this command in your terminal:

#+begin_src bash
> dotnet add package RSML
#+end_src

If you wish to specify a version, use the ~--version~ flag, as in:

#+begin_src bash
> dotnet add package RSML --version 1.0.5
#+end_src

** 🟡 NuGet Package (Visual Studio Package Manager)
If you are using *Visual Studio*, you may use its built-in package manager console or the graphical NuGet interface.

To use the first, run:

#+begin_src powershell
PM> NuGet\Install-Package RSML -Version 1.0.5
#+end_src

** 🟠 NuGet Package (Project File)
If none of the previous options satisfy you, you may also directly edit the *project file* (~.csproj~ file) by adding the following line to an ~ItemGroup~:

#+begin_src xml
<PackageReference Include="RSML" Version="1.0.5" />
#+end_src

** 🔴 Project Reference (Stable Version) - *Not Recommended*
In [[https://github.com/OceanApocalypseStudios/RedSeaMarkupLanguage][our GitHub repository]], select a *tag* in ~vX.X.X~ format (in Regex: ~v[0-9]+\.[0-9]+\.[0-9]+~), as those are the stable versions.

Clone the repository at that time in Git history and reference the project locally in the solution.

** 🟣 Project Reference (Nightly Version) - *Not Recommended*
If for some reason, the program you're developing requires to be up to date with the latest RSML updates, as small as they might be, clone our repository and reference the project manually.

👉 *After it's installed, [[file:PostInstallation.org][you may start using it]].*
