<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup Label="General Properties">
		<TargetFrameworks>net10.0;netstandard2.0</TargetFrameworks>
		<Nullable>enable</Nullable>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<LangVersion>latest</LangVersion>

		<OutputType>Library</OutputType>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>

		<RootNamespace>OceanApocalypseStudios.RSML.Sdk</RootNamespace>

		<Platforms>AnyCPU;ARM64;x64;x86</Platforms>
	</PropertyGroup>

	<PropertyGroup Label="NuGet Package Setup">
		<GeneratePackageOnBuild>True</GeneratePackageOnBuild>

		<PackageId>OceanApocalypseStudios.RSML.Sdk</PackageId>
		<Title>Red Sea Markup Language SDK</Title>
		<Authors>OceanApocalypseStudios</Authors>
		<Company>OceanApocalypseStudios</Company>
		<NeutralLanguage>en</NeutralLanguage>

		<!-- !!! DON'T FORGET TO EDIT THE VERSION AND NOTES HERE !!! -->
		<Version>1.0.0-prerelease1</Version>
		<PackageReleaseNotes>RSML SDK v2.0.0 is here!</PackageReleaseNotes>

		<Description>The plug and play SDK for the only markup language that dynamically interprets different logic paths based on an host's OS and CPU architecture.</Description>
		<Copyright>Copyright (c) 2025 OceanApocalypseStudios</Copyright>
		<PackageProjectUrl>https://oceanapocalypsestudios.org/rsml-docs/</PackageProjectUrl>
		<PackageIcon>icon.png</PackageIcon>
		<RepositoryUrl>https://github.com/OceanApocalypseStudios/RedSeaMarkupLanguage/</RepositoryUrl>
		<RepositoryType>git</RepositoryType>
		<PackageTags>markup;language;logic;logic-path;system;host;rsml;rsea;decision;oss</PackageTags>
		<PackageRequireLicenseAcceptance>true</PackageRequireLicenseAcceptance>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
	</PropertyGroup>

	<PropertyGroup Label="Windows" Condition="'$(OS)' == 'Windows_NT'">
		<DefineConstants>WINDOWS;$(DefineConstants)</DefineConstants>
	</PropertyGroup>

	<PropertyGroup Label="Not Windows" Condition="'$(OS)' != 'Windows_NT'">
		<DefineConstants>NOT_WINDOWS;$(DefineConstants)</DefineConstants>
	</PropertyGroup>

	<PropertyGroup Label="Debug Build" Condition="'$(Configuration)' == 'Debug'">
		<DebugType>full</DebugType>
		<CheckForOverflowUnderflow>True</CheckForOverflowUnderflow>
	</PropertyGroup>

	<PropertyGroup Label="Release (Optimized) Build" Condition="'$(Configuration)' == 'Release'">
		<DebugType>none</DebugType>
		<Optimize>true</Optimize>
	</PropertyGroup>

	<ItemGroup Label="Resources">
		<None Include="..\..\assets\icon.png">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
			<Visible>false</Visible>
		</None>
		<None Include="..\..\README.md">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
			<Visible>false</Visible>
		</None>
	</ItemGroup>

	<ItemGroup Label="When not .NET Standard 2.0" Condition="'$(TargetFramework)' != 'netstandard2.0'">
		<Compile Remove="**\*.NetStd2.cs" Visible="true" />
	</ItemGroup>

	<ItemGroup Label="When not .NET 10" Condition="'$(TargetFramework)' != 'net10.0'">
		<Compile Remove="**\*.Net10.cs" Visible="true" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\RSML\RSML.csproj" />
	</ItemGroup>

</Project>
