### YamlMime:ManagedReference
items:
- uid: OceanApocalypseStudios.RSML.ToolchainConfiguration
  commentId: T:OceanApocalypseStudios.RSML.ToolchainConfiguration
  id: ToolchainConfiguration
  parent: OceanApocalypseStudios.RSML
  children:
  - OceanApocalypseStudios.RSML.ToolchainConfiguration.DisableExtensionProcessing
  - OceanApocalypseStudios.RSML.ToolchainConfiguration.AllowOnlyOASExtensions
  - OceanApocalypseStudios.RSML.ToolchainConfiguration.IgnoreBrokenExtensions
  - OceanApocalypseStudios.RSML.ToolchainConfiguration.IgnoreDuplicatedExtensions
  - OceanApocalypseStudios.RSML.ToolchainConfiguration.IgnoreAllExtensibilityErrors
  langs:
  - csharp
  - vb
  name: ToolchainConfiguration
  nameWithType: ToolchainConfiguration
  fullName: OceanApocalypseStudios.RSML.ToolchainConfiguration
  type: Enum
  source:
    remote:
      path: src/RSML/ToolchainConfiguration.cs
      branch: dev
      repo: https://github.com/OceanApocalypseStudios/RedSeaMarkupLanguage.git
    id: ToolchainConfiguration
    path: ../src/RSML/ToolchainConfiguration.cs
    startLine: 8
  assemblies:
  - RSML
  namespace: OceanApocalypseStudios.RSML
  summary: Configuration options for a <xref href="OceanApocalypseStudios.RSML.IToolchainComponent" data-throw-if-not-resolved="false"></xref>.
  example: []
  syntax:
    content: >-
      [Flags]

      public enum ToolchainConfiguration
    content.vb: >-
      <Flags>

      Public Enum ToolchainConfiguration
  attributes:
  - type: System.FlagsAttribute
    ctor: System.FlagsAttribute.#ctor
    arguments: []
- uid: OceanApocalypseStudios.RSML.ToolchainConfiguration.DisableExtensionProcessing
  commentId: F:OceanApocalypseStudios.RSML.ToolchainConfiguration.DisableExtensionProcessing
  id: DisableExtensionProcessing
  parent: OceanApocalypseStudios.RSML.ToolchainConfiguration
  langs:
  - csharp
  - vb
  name: DisableExtensionProcessing
  nameWithType: ToolchainConfiguration.DisableExtensionProcessing
  fullName: OceanApocalypseStudios.RSML.ToolchainConfiguration.DisableExtensionProcessing
  type: Field
  source:
    remote:
      path: src/RSML/ToolchainConfiguration.cs
      branch: dev
      repo: https://github.com/OceanApocalypseStudios/RedSeaMarkupLanguage.git
    id: DisableExtensionProcessing
    path: ../src/RSML/ToolchainConfiguration.cs
    startLine: 22
  assemblies:
  - RSML
  namespace: OceanApocalypseStudios.RSML
  summary: Optimizes the toolchain pipeline by disabling extension processing.
  remarks: >-
    > [!WARNING]

    > This completely disables extensions, but does not warn you if there are active extensions,

    > meaning sometimes you might be wondering why your extension is not working when, in reality,

    you've enabled this configuration.

    > [!TIP]

    > This configuration is automatically enabled when no extensions are enabled.
  example: []
  syntax:
    content: DisableExtensionProcessing = 1
    return:
      type: OceanApocalypseStudios.RSML.ToolchainConfiguration
- uid: OceanApocalypseStudios.RSML.ToolchainConfiguration.AllowOnlyOASExtensions
  commentId: F:OceanApocalypseStudios.RSML.ToolchainConfiguration.AllowOnlyOASExtensions
  id: AllowOnlyOASExtensions
  parent: OceanApocalypseStudios.RSML.ToolchainConfiguration
  langs:
  - csharp
  - vb
  name: AllowOnlyOASExtensions
  nameWithType: ToolchainConfiguration.AllowOnlyOASExtensions
  fullName: OceanApocalypseStudios.RSML.ToolchainConfiguration.AllowOnlyOASExtensions
  type: Field
  source:
    remote:
      path: src/RSML/ToolchainConfiguration.cs
      branch: dev
      repo: https://github.com/OceanApocalypseStudios/RedSeaMarkupLanguage.git
    id: AllowOnlyOASExtensions
    path: ../src/RSML/ToolchainConfiguration.cs
    startLine: 32
  assemblies:
  - RSML
  namespace: OceanApocalypseStudios.RSML
  summary: Only allows OceanApocalypseStudios extensions, leading to an error if any non-OAS extension is active.
  remarks: >-
    > [!NOTE]

    > When used alongside <xref href="OceanApocalypseStudios.RSML.ToolchainConfiguration.IgnoreAllExtensibilityErrors" data-throw-if-not-resolved="false"></xref>, the non-OAS extensions will be disabled, but

    > no errors will be thrown.
  example: []
  syntax:
    content: AllowOnlyOASExtensions = 2
    return:
      type: OceanApocalypseStudios.RSML.ToolchainConfiguration
- uid: OceanApocalypseStudios.RSML.ToolchainConfiguration.IgnoreBrokenExtensions
  commentId: F:OceanApocalypseStudios.RSML.ToolchainConfiguration.IgnoreBrokenExtensions
  id: IgnoreBrokenExtensions
  parent: OceanApocalypseStudios.RSML.ToolchainConfiguration
  langs:
  - csharp
  - vb
  name: IgnoreBrokenExtensions
  nameWithType: ToolchainConfiguration.IgnoreBrokenExtensions
  fullName: OceanApocalypseStudios.RSML.ToolchainConfiguration.IgnoreBrokenExtensions
  type: Field
  source:
    remote:
      path: src/RSML/ToolchainConfiguration.cs
      branch: dev
      repo: https://github.com/OceanApocalypseStudios/RedSeaMarkupLanguage.git
    id: IgnoreBrokenExtensions
    path: ../src/RSML/ToolchainConfiguration.cs
    startLine: 37
  assemblies:
  - RSML
  namespace: OceanApocalypseStudios.RSML
  summary: Ignores all errors caused by broken or faulty extensions.
  example: []
  syntax:
    content: IgnoreBrokenExtensions = 4
    return:
      type: OceanApocalypseStudios.RSML.ToolchainConfiguration
- uid: OceanApocalypseStudios.RSML.ToolchainConfiguration.IgnoreDuplicatedExtensions
  commentId: F:OceanApocalypseStudios.RSML.ToolchainConfiguration.IgnoreDuplicatedExtensions
  id: IgnoreDuplicatedExtensions
  parent: OceanApocalypseStudios.RSML.ToolchainConfiguration
  langs:
  - csharp
  - vb
  name: IgnoreDuplicatedExtensions
  nameWithType: ToolchainConfiguration.IgnoreDuplicatedExtensions
  fullName: OceanApocalypseStudios.RSML.ToolchainConfiguration.IgnoreDuplicatedExtensions
  type: Field
  source:
    remote:
      path: src/RSML/ToolchainConfiguration.cs
      branch: dev
      repo: https://github.com/OceanApocalypseStudios/RedSeaMarkupLanguage.git
    id: IgnoreDuplicatedExtensions
    path: ../src/RSML/ToolchainConfiguration.cs
    startLine: 42
  assemblies:
  - RSML
  namespace: OceanApocalypseStudios.RSML
  summary: Ignores all errors caused by injecting already injected extensions.
  example: []
  syntax:
    content: IgnoreDuplicatedExtensions = 8
    return:
      type: OceanApocalypseStudios.RSML.ToolchainConfiguration
- uid: OceanApocalypseStudios.RSML.ToolchainConfiguration.IgnoreAllExtensibilityErrors
  commentId: F:OceanApocalypseStudios.RSML.ToolchainConfiguration.IgnoreAllExtensibilityErrors
  id: IgnoreAllExtensibilityErrors
  parent: OceanApocalypseStudios.RSML.ToolchainConfiguration
  langs:
  - csharp
  - vb
  name: IgnoreAllExtensibilityErrors
  nameWithType: ToolchainConfiguration.IgnoreAllExtensibilityErrors
  fullName: OceanApocalypseStudios.RSML.ToolchainConfiguration.IgnoreAllExtensibilityErrors
  type: Field
  source:
    remote:
      path: src/RSML/ToolchainConfiguration.cs
      branch: dev
      repo: https://github.com/OceanApocalypseStudios/RedSeaMarkupLanguage.git
    id: IgnoreAllExtensibilityErrors
    path: ../src/RSML/ToolchainConfiguration.cs
    startLine: 52
  assemblies:
  - RSML
  namespace: OceanApocalypseStudios.RSML
  summary: Ignores all errors thrown during pipeline creation and pipeline execution.
  remarks: >-
    > [!CAUTION]

    > This option is only needed in beyond extremely rare occasions.

    > It emulates RSML v1.x.x behavior.
  example: []
  syntax:
    content: IgnoreAllExtensibilityErrors = IgnoreBrokenExtensions | IgnoreDuplicatedExtensions
    return:
      type: OceanApocalypseStudios.RSML.ToolchainConfiguration
    content.vb: IgnoreAllExtensibilityErrors = IgnoreBrokenExtensions Or IgnoreDuplicatedExtensions
references:
- uid: OceanApocalypseStudios.RSML.IToolchainComponent
  commentId: T:OceanApocalypseStudios.RSML.IToolchainComponent
  parent: OceanApocalypseStudios.RSML
  href: OceanApocalypseStudios.RSML.IToolchainComponent.html
  name: IToolchainComponent
  nameWithType: IToolchainComponent
  fullName: OceanApocalypseStudios.RSML.IToolchainComponent
- uid: OceanApocalypseStudios.RSML
  commentId: N:OceanApocalypseStudios.RSML
  href: OceanApocalypseStudios.html
  name: OceanApocalypseStudios.RSML
  nameWithType: OceanApocalypseStudios.RSML
  fullName: OceanApocalypseStudios.RSML
  spec.csharp:
  - uid: OceanApocalypseStudios
    name: OceanApocalypseStudios
    href: OceanApocalypseStudios.html
  - name: .
  - uid: OceanApocalypseStudios.RSML
    name: RSML
    href: OceanApocalypseStudios.RSML.html
  spec.vb:
  - uid: OceanApocalypseStudios
    name: OceanApocalypseStudios
    href: OceanApocalypseStudios.html
  - name: .
  - uid: OceanApocalypseStudios.RSML
    name: RSML
    href: OceanApocalypseStudios.RSML.html
- uid: OceanApocalypseStudios.RSML.ToolchainConfiguration
  commentId: T:OceanApocalypseStudios.RSML.ToolchainConfiguration
  parent: OceanApocalypseStudios.RSML
  href: OceanApocalypseStudios.RSML.ToolchainConfiguration.html
  name: ToolchainConfiguration
  nameWithType: ToolchainConfiguration
  fullName: OceanApocalypseStudios.RSML.ToolchainConfiguration
- uid: OceanApocalypseStudios.RSML.ToolchainConfiguration.IgnoreAllExtensibilityErrors
  commentId: F:OceanApocalypseStudios.RSML.ToolchainConfiguration.IgnoreAllExtensibilityErrors
  href: OceanApocalypseStudios.RSML.ToolchainConfiguration.html#OceanApocalypseStudios_RSML_ToolchainConfiguration_IgnoreAllExtensibilityErrors
  name: IgnoreAllExtensibilityErrors
  nameWithType: ToolchainConfiguration.IgnoreAllExtensibilityErrors
  fullName: OceanApocalypseStudios.RSML.ToolchainConfiguration.IgnoreAllExtensibilityErrors
memberLayout: SeparatePages
