### YamlMime:ManagedReference
items:
- uid: OceanApocalypseStudios.RSML.Sdk.ToolchainConfiguration
  commentId: T:OceanApocalypseStudios.RSML.Sdk.ToolchainConfiguration
  id: ToolchainConfiguration
  parent: OceanApocalypseStudios.RSML.Sdk
  children:
  - OceanApocalypseStudios.RSML.Sdk.ToolchainConfiguration.AllowOnlyOASExtensions
  - OceanApocalypseStudios.RSML.Sdk.ToolchainConfiguration.DisableExtensionProcessing
  - OceanApocalypseStudios.RSML.Sdk.ToolchainConfiguration.DoNotFreezeComponentsOnLastInjection
  - OceanApocalypseStudios.RSML.Sdk.ToolchainConfiguration.SilentlyIgnoreAllErrors
  - OceanApocalypseStudios.RSML.Sdk.ToolchainConfiguration.SilentlyIgnoreBrokenExtensions
  - OceanApocalypseStudios.RSML.Sdk.ToolchainConfiguration.SilentlyIgnoreDuplicatedConfigurations
  - OceanApocalypseStudios.RSML.Sdk.ToolchainConfiguration.SilentlyIgnoreDuplicatedExtensions
  langs:
  - csharp
  - vb
  name: ToolchainConfiguration
  nameWithType: ToolchainConfiguration
  fullName: OceanApocalypseStudios.RSML.Sdk.ToolchainConfiguration
  type: Enum
  source:
    remote:
      path: src/RSML/Sdk/ToolchainConfiguration.cs
      branch: docs
      repo: https://github.com/OceanApocalypseStudios/RedSeaMarkupLanguage.git
    id: ToolchainConfiguration
    path: ../src/RSML/Sdk/ToolchainConfiguration.cs
    startLine: 5
  assemblies:
  - RSML
  namespace: OceanApocalypseStudios.RSML.Sdk
  summary: Configuration options for a <xref href="OceanApocalypseStudios.RSML.Sdk.ToolchainExecutionPlan" data-throw-if-not-resolved="false"></xref>, usually passed via a <xref href="OceanApocalypseStudios.RSML.Sdk.ToolchainExecutionPlanBuilder" data-throw-if-not-resolved="false"></xref>.
  example: []
  syntax:
    content: public enum ToolchainConfiguration
    content.vb: Public Enum ToolchainConfiguration
- uid: OceanApocalypseStudios.RSML.Sdk.ToolchainConfiguration.DisableExtensionProcessing
  commentId: F:OceanApocalypseStudios.RSML.Sdk.ToolchainConfiguration.DisableExtensionProcessing
  id: DisableExtensionProcessing
  parent: OceanApocalypseStudios.RSML.Sdk.ToolchainConfiguration
  langs:
  - csharp
  - vb
  name: DisableExtensionProcessing
  nameWithType: ToolchainConfiguration.DisableExtensionProcessing
  fullName: OceanApocalypseStudios.RSML.Sdk.ToolchainConfiguration.DisableExtensionProcessing
  type: Field
  source:
    remote:
      path: src/RSML/Sdk/ToolchainConfiguration.cs
      branch: docs
      repo: https://github.com/OceanApocalypseStudios/RedSeaMarkupLanguage.git
    id: DisableExtensionProcessing
    path: ../src/RSML/Sdk/ToolchainConfiguration.cs
    startLine: 21
  assemblies:
  - RSML
  namespace: OceanApocalypseStudios.RSML.Sdk
  summary: Optimizes the toolchain pipeline by disabling extension processing.
  remarks: >-
    > [!WARNING]

    > This completely disables extensions, but does not warn you if there are active extensions,

    > meaning sometimes you might be wondering why your extension is not working when, in reality,

    you've enabled this configuration.

    > [!IMPORTANT]

    > This configuration is automatically enabled when no extensions are enabled, meaning that

    > if you pass this configuration manually when no extensions are active, you will cause RSML

    > to error out due to duplicated configuration, unless <xref href="OceanApocalypseStudios.RSML.Sdk.ToolchainConfiguration.SilentlyIgnoreDuplicatedConfigurations" data-throw-if-not-resolved="false"></xref>

    > or <xref href="OceanApocalypseStudios.RSML.Sdk.ToolchainConfiguration.SilentlyIgnoreAllErrors" data-throw-if-not-resolved="false"></xref> are enabled.
  example: []
  syntax:
    content: DisableExtensionProcessing = 0
    return:
      type: OceanApocalypseStudios.RSML.Sdk.ToolchainConfiguration
- uid: OceanApocalypseStudios.RSML.Sdk.ToolchainConfiguration.AllowOnlyOASExtensions
  commentId: F:OceanApocalypseStudios.RSML.Sdk.ToolchainConfiguration.AllowOnlyOASExtensions
  id: AllowOnlyOASExtensions
  parent: OceanApocalypseStudios.RSML.Sdk.ToolchainConfiguration
  langs:
  - csharp
  - vb
  name: AllowOnlyOASExtensions
  nameWithType: ToolchainConfiguration.AllowOnlyOASExtensions
  fullName: OceanApocalypseStudios.RSML.Sdk.ToolchainConfiguration.AllowOnlyOASExtensions
  type: Field
  source:
    remote:
      path: src/RSML/Sdk/ToolchainConfiguration.cs
      branch: docs
      repo: https://github.com/OceanApocalypseStudios/RedSeaMarkupLanguage.git
    id: AllowOnlyOASExtensions
    path: ../src/RSML/Sdk/ToolchainConfiguration.cs
    startLine: 31
  assemblies:
  - RSML
  namespace: OceanApocalypseStudios.RSML.Sdk
  summary: Only allows OceanApocalypseStudios extensions, leading to an error if any non-OAS extension is active.
  remarks: >-
    > [!NOTE]

    > When used alongside <xref href="OceanApocalypseStudios.RSML.Sdk.ToolchainConfiguration.SilentlyIgnoreAllErrors" data-throw-if-not-resolved="false"></xref>, the non-OAS extensions will be disabled, but

    > no errors will be thrown.
  example: []
  syntax:
    content: AllowOnlyOASExtensions = 1
    return:
      type: OceanApocalypseStudios.RSML.Sdk.ToolchainConfiguration
- uid: OceanApocalypseStudios.RSML.Sdk.ToolchainConfiguration.DoNotFreezeComponentsOnLastInjection
  commentId: F:OceanApocalypseStudios.RSML.Sdk.ToolchainConfiguration.DoNotFreezeComponentsOnLastInjection
  id: DoNotFreezeComponentsOnLastInjection
  parent: OceanApocalypseStudios.RSML.Sdk.ToolchainConfiguration
  langs:
  - csharp
  - vb
  name: DoNotFreezeComponentsOnLastInjection
  nameWithType: ToolchainConfiguration.DoNotFreezeComponentsOnLastInjection
  fullName: OceanApocalypseStudios.RSML.Sdk.ToolchainConfiguration.DoNotFreezeComponentsOnLastInjection
  type: Field
  source:
    remote:
      path: src/RSML/Sdk/ToolchainConfiguration.cs
      branch: docs
      repo: https://github.com/OceanApocalypseStudios/RedSeaMarkupLanguage.git
    id: DoNotFreezeComponentsOnLastInjection
    path: ../src/RSML/Sdk/ToolchainConfiguration.cs
    startLine: 36
  assemblies:
  - RSML
  namespace: OceanApocalypseStudios.RSML.Sdk
  summary: Overrides the default behavior of freezing all toolchain components after the last injection.
  example: []
  syntax:
    content: DoNotFreezeComponentsOnLastInjection = 2
    return:
      type: OceanApocalypseStudios.RSML.Sdk.ToolchainConfiguration
- uid: OceanApocalypseStudios.RSML.Sdk.ToolchainConfiguration.SilentlyIgnoreBrokenExtensions
  commentId: F:OceanApocalypseStudios.RSML.Sdk.ToolchainConfiguration.SilentlyIgnoreBrokenExtensions
  id: SilentlyIgnoreBrokenExtensions
  parent: OceanApocalypseStudios.RSML.Sdk.ToolchainConfiguration
  langs:
  - csharp
  - vb
  name: SilentlyIgnoreBrokenExtensions
  nameWithType: ToolchainConfiguration.SilentlyIgnoreBrokenExtensions
  fullName: OceanApocalypseStudios.RSML.Sdk.ToolchainConfiguration.SilentlyIgnoreBrokenExtensions
  type: Field
  source:
    remote:
      path: src/RSML/Sdk/ToolchainConfiguration.cs
      branch: docs
      repo: https://github.com/OceanApocalypseStudios/RedSeaMarkupLanguage.git
    id: SilentlyIgnoreBrokenExtensions
    path: ../src/RSML/Sdk/ToolchainConfiguration.cs
    startLine: 38
  assemblies:
  - RSML
  namespace: OceanApocalypseStudios.RSML.Sdk
  syntax:
    content: SilentlyIgnoreBrokenExtensions = 3
    return:
      type: OceanApocalypseStudios.RSML.Sdk.ToolchainConfiguration
- uid: OceanApocalypseStudios.RSML.Sdk.ToolchainConfiguration.SilentlyIgnoreDuplicatedExtensions
  commentId: F:OceanApocalypseStudios.RSML.Sdk.ToolchainConfiguration.SilentlyIgnoreDuplicatedExtensions
  id: SilentlyIgnoreDuplicatedExtensions
  parent: OceanApocalypseStudios.RSML.Sdk.ToolchainConfiguration
  langs:
  - csharp
  - vb
  name: SilentlyIgnoreDuplicatedExtensions
  nameWithType: ToolchainConfiguration.SilentlyIgnoreDuplicatedExtensions
  fullName: OceanApocalypseStudios.RSML.Sdk.ToolchainConfiguration.SilentlyIgnoreDuplicatedExtensions
  type: Field
  source:
    remote:
      path: src/RSML/Sdk/ToolchainConfiguration.cs
      branch: docs
      repo: https://github.com/OceanApocalypseStudios/RedSeaMarkupLanguage.git
    id: SilentlyIgnoreDuplicatedExtensions
    path: ../src/RSML/Sdk/ToolchainConfiguration.cs
    startLine: 39
  assemblies:
  - RSML
  namespace: OceanApocalypseStudios.RSML.Sdk
  syntax:
    content: SilentlyIgnoreDuplicatedExtensions = 4
    return:
      type: OceanApocalypseStudios.RSML.Sdk.ToolchainConfiguration
- uid: OceanApocalypseStudios.RSML.Sdk.ToolchainConfiguration.SilentlyIgnoreDuplicatedConfigurations
  commentId: F:OceanApocalypseStudios.RSML.Sdk.ToolchainConfiguration.SilentlyIgnoreDuplicatedConfigurations
  id: SilentlyIgnoreDuplicatedConfigurations
  parent: OceanApocalypseStudios.RSML.Sdk.ToolchainConfiguration
  langs:
  - csharp
  - vb
  name: SilentlyIgnoreDuplicatedConfigurations
  nameWithType: ToolchainConfiguration.SilentlyIgnoreDuplicatedConfigurations
  fullName: OceanApocalypseStudios.RSML.Sdk.ToolchainConfiguration.SilentlyIgnoreDuplicatedConfigurations
  type: Field
  source:
    remote:
      path: src/RSML/Sdk/ToolchainConfiguration.cs
      branch: docs
      repo: https://github.com/OceanApocalypseStudios/RedSeaMarkupLanguage.git
    id: SilentlyIgnoreDuplicatedConfigurations
    path: ../src/RSML/Sdk/ToolchainConfiguration.cs
    startLine: 40
  assemblies:
  - RSML
  namespace: OceanApocalypseStudios.RSML.Sdk
  syntax:
    content: SilentlyIgnoreDuplicatedConfigurations = 5
    return:
      type: OceanApocalypseStudios.RSML.Sdk.ToolchainConfiguration
- uid: OceanApocalypseStudios.RSML.Sdk.ToolchainConfiguration.SilentlyIgnoreAllErrors
  commentId: F:OceanApocalypseStudios.RSML.Sdk.ToolchainConfiguration.SilentlyIgnoreAllErrors
  id: SilentlyIgnoreAllErrors
  parent: OceanApocalypseStudios.RSML.Sdk.ToolchainConfiguration
  langs:
  - csharp
  - vb
  name: SilentlyIgnoreAllErrors
  nameWithType: ToolchainConfiguration.SilentlyIgnoreAllErrors
  fullName: OceanApocalypseStudios.RSML.Sdk.ToolchainConfiguration.SilentlyIgnoreAllErrors
  type: Field
  source:
    remote:
      path: src/RSML/Sdk/ToolchainConfiguration.cs
      branch: docs
      repo: https://github.com/OceanApocalypseStudios/RedSeaMarkupLanguage.git
    id: SilentlyIgnoreAllErrors
    path: ../src/RSML/Sdk/ToolchainConfiguration.cs
    startLine: 50
  assemblies:
  - RSML
  namespace: OceanApocalypseStudios.RSML.Sdk
  summary: Ignores all errors thrown during pipeline creation and pipeline execution.
  remarks: >-
    > [!CAUTION]

    > This option is only needed in beyond extremely rare occasions.

    > It emulates RSML v1.x.x behavior.
  example: []
  syntax:
    content: SilentlyIgnoreAllErrors = 6
    return:
      type: OceanApocalypseStudios.RSML.Sdk.ToolchainConfiguration
references:
- uid: OceanApocalypseStudios.RSML.Sdk.ToolchainExecutionPlan
  commentId: T:OceanApocalypseStudios.RSML.Sdk.ToolchainExecutionPlan
  parent: OceanApocalypseStudios.RSML.Sdk
  href: OceanApocalypseStudios.RSML.Sdk.ToolchainExecutionPlan.html
  name: ToolchainExecutionPlan
  nameWithType: ToolchainExecutionPlan
  fullName: OceanApocalypseStudios.RSML.Sdk.ToolchainExecutionPlan
- uid: OceanApocalypseStudios.RSML.Sdk.ToolchainExecutionPlanBuilder
  commentId: T:OceanApocalypseStudios.RSML.Sdk.ToolchainExecutionPlanBuilder
  parent: OceanApocalypseStudios.RSML.Sdk
  href: OceanApocalypseStudios.RSML.Sdk.ToolchainExecutionPlanBuilder.html
  name: ToolchainExecutionPlanBuilder
  nameWithType: ToolchainExecutionPlanBuilder
  fullName: OceanApocalypseStudios.RSML.Sdk.ToolchainExecutionPlanBuilder
- uid: OceanApocalypseStudios.RSML.Sdk
  commentId: N:OceanApocalypseStudios.RSML.Sdk
  href: OceanApocalypseStudios.html
  name: OceanApocalypseStudios.RSML.Sdk
  nameWithType: OceanApocalypseStudios.RSML.Sdk
  fullName: OceanApocalypseStudios.RSML.Sdk
  spec.csharp:
  - uid: OceanApocalypseStudios
    name: OceanApocalypseStudios
    href: OceanApocalypseStudios.html
  - name: .
  - uid: OceanApocalypseStudios.RSML
    name: RSML
    href: OceanApocalypseStudios.RSML.html
  - name: .
  - uid: OceanApocalypseStudios.RSML.Sdk
    name: Sdk
    href: OceanApocalypseStudios.RSML.Sdk.html
  spec.vb:
  - uid: OceanApocalypseStudios
    name: OceanApocalypseStudios
    href: OceanApocalypseStudios.html
  - name: .
  - uid: OceanApocalypseStudios.RSML
    name: RSML
    href: OceanApocalypseStudios.RSML.html
  - name: .
  - uid: OceanApocalypseStudios.RSML.Sdk
    name: Sdk
    href: OceanApocalypseStudios.RSML.Sdk.html
- uid: OceanApocalypseStudios.RSML.Sdk.ToolchainConfiguration.SilentlyIgnoreDuplicatedConfigurations
  commentId: F:OceanApocalypseStudios.RSML.Sdk.ToolchainConfiguration.SilentlyIgnoreDuplicatedConfigurations
  href: OceanApocalypseStudios.RSML.Sdk.ToolchainConfiguration.html#OceanApocalypseStudios_RSML_Sdk_ToolchainConfiguration_SilentlyIgnoreDuplicatedConfigurations
  name: SilentlyIgnoreDuplicatedConfigurations
  nameWithType: ToolchainConfiguration.SilentlyIgnoreDuplicatedConfigurations
  fullName: OceanApocalypseStudios.RSML.Sdk.ToolchainConfiguration.SilentlyIgnoreDuplicatedConfigurations
- uid: OceanApocalypseStudios.RSML.Sdk.ToolchainConfiguration.SilentlyIgnoreAllErrors
  commentId: F:OceanApocalypseStudios.RSML.Sdk.ToolchainConfiguration.SilentlyIgnoreAllErrors
  href: OceanApocalypseStudios.RSML.Sdk.ToolchainConfiguration.html#OceanApocalypseStudios_RSML_Sdk_ToolchainConfiguration_SilentlyIgnoreAllErrors
  name: SilentlyIgnoreAllErrors
  nameWithType: ToolchainConfiguration.SilentlyIgnoreAllErrors
  fullName: OceanApocalypseStudios.RSML.Sdk.ToolchainConfiguration.SilentlyIgnoreAllErrors
- uid: OceanApocalypseStudios.RSML.Sdk.ToolchainConfiguration
  commentId: T:OceanApocalypseStudios.RSML.Sdk.ToolchainConfiguration
  parent: OceanApocalypseStudios.RSML.Sdk
  href: OceanApocalypseStudios.RSML.Sdk.ToolchainConfiguration.html
  name: ToolchainConfiguration
  nameWithType: ToolchainConfiguration
  fullName: OceanApocalypseStudios.RSML.Sdk.ToolchainConfiguration
memberLayout: SeparatePages
